language: java
sudo: required
services:
  - docker
jdk:
- openjdk8
install:
- export GNUPGHOME="$(mktemp -d)"
- eval $(gpg-agent --daemon)
- gpg --batch --gen-key gpg.key
-  gpg --list-keys
- ./mvnw -B -q -Pdocker-gitlab dependency:go-offline verify -DskipTests -Ddocker.skip -Darguments=-Dgpg.passphrase=thephrase
script:
- ./mvnw -B -V -Pdocker-gitlab verify
