language: java
sudo: required
services:
  - docker
jdk:
- openjdk8
install:
- export GNUPGHOME="$(mktemp -d)"
- cat >foo <<EOF
     %echo Generating a basic OpenPGP key
     Key-Type: DSA
     Key-Length: 1024
     Subkey-Type: ELG-E
     Subkey-Length: 1024
     Name-Real: Joe Tester
     Name-Comment: with  passphrase
     Name-Email: joe@foo.bar
     Expire-Date: 0
     Passphrase: abc
     # Do a commit here, so that we can later print "done" :-)
     %commit
     %echo done
   EOF
- gpg --batch --generate-key foo
-  gpg --list-keys
- ./mvnw -B -q -Pdocker-gitlab dependency:go-offline verify -DskipTests -Ddocker.skip -Darguments=-Dgpg.passphrase=thephrase
script:
- ./mvnw -B -V -Pdocker-gitlab verify
