language: java
sudo: required
services:
  - docker
jdk:
- openjdk8
install:
- export GNUPGHOME="$(mktemp -d)"
- eval $(gpg-agent --daemon)
- gpg --batch --gen-key gpg.key
-  gpg --list-keys
- ./mvnw  -Pdocker-gitlab dependency:go-offline verify -DskipTests -Ddocker.skip -Darguments=-Dgpg.passphrase=abc
script:
- ./mvnw  -V -Pdocker-gitlab verify -Darguments=-Dgpg.passphrase=abc
